 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.familia.mx.vies;

import com.familia.mx.bo.RecetaBO;
import com.familia.mx.entity.Receta;
import com.familia.mx.entity.Recetas;
import javax.swing.JOptionPane;

/**
 *
 * @author luis_
 */
public class FormularioReceta extends javax.swing.JFrame {

    /**
     * Creates new form FormularioReceta
     */
    private RecetaBO recetabo = new RecetaBO();
    
    public FormularioReceta() {
        initComponents();
        listarReceta();
        idMax();
        setTitle("FORMULARIO RECETARIO");
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    // nuevo
    public void listarReceta(){
        
       recetabo.listarReceta(tbRecetario);
    }
    
    public void idMax(){
        txtId_recetario.setText(recetabo.getMaxid()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId_recetario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtId_comentario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtId_clasificacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTiempoEnCocina = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTiempoDeCoccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUtencilios = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtProcedimiento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNotas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRecetario = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel1.setText("ID recetario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 30));

        txtId_recetario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtId_recetario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_recetarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtId_recetario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 330, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel3.setText("Formulario del Recetario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 260, 30));

        txtId_comentario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtId_comentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 330, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel2.setText("ID comentario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 30));

        txtId_clasificacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtId_clasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 330, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel4.setText("ID clasificacion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, 30));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 330, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, 30));

        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 330, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel6.setText("Descripcion:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 30));

        txtTiempoEnCocina.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtTiempoEnCocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 330, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel7.setText("Tiempo en cocina:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, 30));

        txtTiempoDeCoccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtTiempoDeCoccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 330, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel8.setText("Tiempo de cocción:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 210, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel9.setText("Utencilios:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 210, -1));

        txtUtencilios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtUtencilios, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 330, -1));

        jLabel10.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel10.setText("Procedimiento:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 210, -1));

        txtProcedimiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtProcedimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 330, -1));

        jLabel11.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel11.setText("Notas:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 210, -1));

        txtNotas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 330, -1));

        tbRecetario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbRecetario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRecetarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbRecetario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 460, 430));

        btnSalir.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 140, 50));

        btnAgregar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 140, 50));

        btnModificar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 170, 50));

        btnEliminar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        btnEliminar.setText("eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 140, 50));

        btnLimpiar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        btnLimpiar.setText("limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 140, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtId_recetarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_recetarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_recetarioActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       if(txtId_recetario.getText().isEmpty() || txtId_comentario.getText().isEmpty() || txtId_clasificacion.getText().isEmpty() || txtNombre.getText().isEmpty()
               || txtDescripcion.getText().isEmpty() || txtTiempoEnCocina.getText().isEmpty()|| txtTiempoDeCoccion.getText().isEmpty() || txtUtencilios.getText().isEmpty()
               || txtProcedimiento.getText().isEmpty() || txtNotas.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "llene todos los campos ");
       }else{
            Recetas recetario = new Recetas();
            recetario.setId_recetario(Integer.parseInt(txtId_recetario.getText()));
            recetario.setNombre_receta(txtNombre.getText());
            recetario.setDescripcion_receta(txtDescripcion.getText());
            recetario.setTiempo_en_cocina(txtTiempoEnCocina.getText());
            recetario.setTiempo_coccion(txtTiempoDeCoccion.getText());
            recetario.setUtencilios(txtUtencilios.getText());
            recetario.setProcedimiento_recetas(txtProcedimiento.getText());
            recetario.setNotas(txtNotas.getText());
           String mensaje = recetabo.agregarReceta(recetario);
           JOptionPane.showMessageDialog(null, mensaje);
           limpiar();
           listarReceta();
       }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       if(txtId_recetario.getText().isEmpty() || txtId_comentario.getText().isEmpty() || txtId_clasificacion.getText().isEmpty() || txtNombre.getText().isEmpty()
               || txtDescripcion.getText().isEmpty() || txtTiempoEnCocina.getText().isEmpty()|| txtTiempoDeCoccion.getText().isEmpty() || txtUtencilios.getText().isEmpty()
               || txtProcedimiento.getText().isEmpty() || txtNotas.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "llene todos los campos ");
       }else{
          // String mensaje = recetabo.eliminarReceta(Integer.parseInt(txtId_recetario.getText()));
           Recetas recetario = new Recetas();
           
            recetario.setNombre_receta(txtNombre.getText());
            recetario.setDescripcion_receta(txtDescripcion.getText());
            recetario.setTiempo_en_cocina(txtTiempoEnCocina.getText());
            recetario.setTiempo_coccion(txtTiempoDeCoccion.getText());
            recetario.setUtencilios(txtUtencilios.getText());
            recetario.setProcedimiento_recetas(txtProcedimiento.getText());
             recetario.setNotas(txtNotas.getText());
             String mensaje = recetabo.agregarReceta(recetario);
           JOptionPane.showMessageDialog(null, mensaje);
           limpiar();
           listarReceta();
       }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
         if(txtId_recetario.getText().isEmpty() || txtId_comentario.getText().isEmpty() || txtId_clasificacion.getText().isEmpty() || txtNombre.getText().isEmpty()
               || txtDescripcion.getText().isEmpty() || txtTiempoEnCocina.getText().isEmpty()|| txtTiempoDeCoccion.getText().isEmpty() || txtUtencilios.getText().isEmpty()
               || txtProcedimiento.getText().isEmpty() || txtNotas.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "llene todos los campos ");
       }else{
            Recetas recetario = new Recetas();
            recetario.setId_recetario(Integer.parseInt(txtId_recetario.getText()));
            recetario.setNombre_receta(txtNombre.getText());
            recetario.setDescripcion_receta(txtDescripcion.getText());
            recetario.setTiempo_en_cocina(txtTiempoEnCocina.getText());
            recetario.setTiempo_coccion(txtTiempoDeCoccion.getText());
            recetario.setUtencilios(txtUtencilios.getText());
            recetario.setProcedimiento_recetas(txtProcedimiento.getText());
            recetario.setNotas(txtNotas.getText());
            String mensaje = recetabo.eliminarReceta(Integer.parseInt(txtId_recetario.getText()));
           //String mensaje = recetabo.agregarReceta(recetario);
           JOptionPane.showMessageDialog(null, mensaje);
           limpiar();
           listarReceta();
       }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tbRecetarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRecetarioMouseClicked
        int  seleccion = tbRecetario.rowAtPoint(evt.getPoint());
        txtId_recetario.setText(tbRecetario.getValueAt(seleccion, 0)+"");
        txtId_comentario.setText(tbRecetario.getValueAt(seleccion, 1)+"");
        txtId_clasificacion.setText(tbRecetario.getValueAt(seleccion, 2)+"");
        txtNombre.setText(tbRecetario.getValueAt(seleccion, 3)+"");
        txtDescripcion.setText(tbRecetario.getValueAt(seleccion, 4)+"");
        txtTiempoEnCocina.setText(tbRecetario.getValueAt(seleccion, 5)+"");
        txtTiempoDeCoccion.setText(tbRecetario.getValueAt(seleccion, 6)+"");
        txtUtencilios.setText(tbRecetario.getValueAt(seleccion, 7)+"");
        txtProcedimiento.setText(tbRecetario.getValueAt(seleccion, 8)+"");
        txtNotas.setText(tbRecetario.getValueAt(seleccion, 9)+"");
    }//GEN-LAST:event_tbRecetarioMouseClicked

    public void limpiar(){
       txtId_recetario.setText("");
       txtId_comentario.setText("");
       txtId_clasificacion.setText("");
       txtNombre.setText("");
       txtDescripcion.setText("");
       txtTiempoEnCocina.setText("");
       txtTiempoDeCoccion.setText("");
       txtUtencilios.setText("");
       txtProcedimiento.setText("");
       txtNotas.setText(""); 
       idMax();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioReceta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbRecetario;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId_clasificacion;
    private javax.swing.JTextField txtId_comentario;
    private javax.swing.JTextField txtId_recetario;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNotas;
    private javax.swing.JTextField txtProcedimiento;
    private javax.swing.JTextField txtTiempoDeCoccion;
    private javax.swing.JTextField txtTiempoEnCocina;
    private javax.swing.JTextField txtUtencilios;
    // End of variables declaration//GEN-END:variables
}
